apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: estafetter-gke-preemptible-killer
  labels:
    app: estafetter-gke-preemptible-killer
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - services
  verbs:
  - delete
  - get
  - list
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: estafetter-gke-preemptible-killer
  labels:
    app: estafetter-gke-preemptible-killer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: estafetter-gke-preemptible-killer
subjects:
- kind: ServiceAccount
  name: estafetter-gke-preemptible-killer
  namespace: estafette
